# Generated by Django 6.0.3 on 2026-03-29 07:47

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('objectives', models.TextField()),
                ('implementation_details', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='proposed', max_length=50)),
                ('title_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('objectives_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('combined_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('last_similarity_check', models.DateTimeField(blank=True, null=True)),
                ('is_flagged_duplicate', models.BooleanField(default=False)),
                ('duplicate_check_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to='accounts.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='projects.project')),
                ('similar_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_flags', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'similar_project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('member', 'Member')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_students', to='projects.project')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('project', 'student')},
            },
        ),
    ]
